# Generated by Django 6.0 on 2025-12-06 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epgp_batch', models.IntegerField(blank=True, default=17)),
                ('epgp_group', models.CharField(blank=True, choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F')], default='A', max_length=1)),
                ('roll_number', models.CharField(max_length=20, null=True, unique=True)),
                ('homeState', models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=100, null=True)),
                ('homeTown', models.CharField(blank=True, max_length=100, null=True)),
                ('currentCity', models.CharField(blank=True, max_length=100, null=True)),
                ('studyCenterState', models.CharField(choices=[('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('TG', 'Telangana'), ('TN', 'Tamil Nadu'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], default='KL', max_length=100)),
                ('studyCenterCity', models.CharField(blank=True, choices=[('Patna', 'Patna'), ('Gaya', 'Gaya'), ('Bhagalpur', 'Bhagalpur'), ('Muzaffarpur', 'Muzaffarpur'), ('Purnia', 'Purnia'), ('Raipur', 'Raipur'), ('Bhilai', 'Bhilai'), ('Bilaspur', 'Bilaspur'), ('Korba', 'Korba'), ('Durg', 'Durg'), ('C', 'C'), ('h', 'h'), ('a', 'a'), ('n', 'n'), ('d', 'd'), ('i', 'i'), ('g', 'g'), ('a', 'a'), ('r', 'r'), ('h', 'h'), ('N', 'N'), ('e', 'e'), ('w', 'w'), (' ', ' '), ('D', 'D'), ('e', 'e'), ('l', 'l'), ('h', 'h'), ('i', 'i'), ('Panaji', 'Panaji'), ('Vasco da Gama', 'Vasco da Gama'), ('Margao', 'Margao'), ('Mapusa', 'Mapusa'), ('Ponda', 'Ponda'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Bhavnagar', 'Bhavnagar'), ('Faridabad', 'Faridabad'), ('Gurugram', 'Gurugram'), ('Panipat', 'Panipat'), ('Ambala', 'Ambala'), ('Yamunanagar', 'Yamunanagar'), ('Ranchi', 'Ranchi'), ('Jamshedpur', 'Jamshedpur'), ('Dhanbad', 'Dhanbad'), ('Bokaro Steel City', 'Bokaro Steel City'), ('Deoghar', 'Deoghar'), ('Bengaluru', 'Bengaluru'), ('Mangaluru', 'Mangaluru'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Thane', 'Thane'), ('Nashik', 'Nashik'), ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Ujjain', 'Ujjain'), ('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Sambalpur', 'Sambalpur'), ('Puri', 'Puri'), ('Ludhiana', 'Ludhiana'), ('Amritsar', 'Amritsar'), ('Jalandhar', 'Jalandhar'), ('Patiala', 'Patiala'), ('Bathinda', 'Bathinda'), ('Jaipur', 'Jaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Bikaner', 'Bikaner'), ('Ajmer', 'Ajmer'), ('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal'), ('Nizamabad', 'Nizamabad'), ('Karimnagar', 'Karimnagar'), ('Ramagundam', 'Ramagundam'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Roorkee', 'Roorkee'), ('Haldwani', 'Haldwani'), ('Kashipur', 'Kashipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Ghaziabad', 'Ghaziabad'), ('Agra', 'Agra'), ('Meerut', 'Meerut'), ('Kolkata', 'Kolkata'), ('Asansol', 'Asansol'), ('Siliguri', 'Siliguri'), ('Durgapur', 'Durgapur'), ('Bardhaman', 'Bardhaman')], max_length=100, null=True)),
                ('studyCenterName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('other', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
