# Generated by Django 6.0 on 2025-12-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_batchinfo_employment_delete_courseinfo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('credits', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='epgp_batch',
            field=models.IntegerField(blank=True, default=17, verbose_name='EPGP Batch'),
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Roll Number (eg 75)'),
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='studyCenterCity',
            field=models.CharField(blank=True, choices=[('Patna', 'Patna'), ('Gaya', 'Gaya'), ('Bhagalpur', 'Bhagalpur'), ('Muzaffarpur', 'Muzaffarpur'), ('Purnia', 'Purnia'), ('Raipur', 'Raipur'), ('Bhilai', 'Bhilai'), ('Bilaspur', 'Bilaspur'), ('Korba', 'Korba'), ('Durg', 'Durg'), ('Chandigarh', 'Chandigarh'), ('CH', 'CH'), ('New Delhi', 'New Delhi'), ('Delhi', 'Delhi'), ('Panaji', 'Panaji'), ('Vasco da Gama', 'Vasco da Gama'), ('Margao', 'Margao'), ('Mapusa', 'Mapusa'), ('Ponda', 'Ponda'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Bhavnagar', 'Bhavnagar'), ('Faridabad', 'Faridabad'), ('Gurugram', 'Gurugram'), ('Panipat', 'Panipat'), ('Ambala', 'Ambala'), ('Yamunanagar', 'Yamunanagar'), ('Ranchi', 'Ranchi'), ('Jamshedpur', 'Jamshedpur'), ('Dhanbad', 'Dhanbad'), ('Bokaro Steel City', 'Bokaro Steel City'), ('Deoghar', 'Deoghar'), ('Bengaluru', 'Bengaluru'), ('Mangaluru', 'Mangaluru'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Thane', 'Thane'), ('Nashik', 'Nashik'), ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Ujjain', 'Ujjain'), ('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Sambalpur', 'Sambalpur'), ('Puri', 'Puri'), ('Ludhiana', 'Ludhiana'), ('Amritsar', 'Amritsar'), ('Jalandhar', 'Jalandhar'), ('Patiala', 'Patiala'), ('Bathinda', 'Bathinda'), ('Jaipur', 'Jaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Bikaner', 'Bikaner'), ('Ajmer', 'Ajmer'), ('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal'), ('Nizamabad', 'Nizamabad'), ('Karimnagar', 'Karimnagar'), ('Ramagundam', 'Ramagundam'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Roorkee', 'Roorkee'), ('Haldwani', 'Haldwani'), ('Kashipur', 'Kashipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Ghaziabad', 'Ghaziabad'), ('Agra', 'Agra'), ('Meerut', 'Meerut'), ('Kolkata', 'Kolkata'), ('Asansol', 'Asansol'), ('Siliguri', 'Siliguri'), ('Durgapur', 'Durgapur'), ('Bardhaman', 'Bardhaman')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ElectiveOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epgp_batch', models.IntegerField(blank=True)),
                ('term', models.IntegerField(blank=True)),
                ('track', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_offerings', to='api.elective')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('elective_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.electiveoffering')),
            ],
        ),
    ]
