# Generated by Django 6.0 on 2025-12-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_elective_alter_batchinfo_epgp_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, choices=[('FAC', 'Finance, Accounting, and Control'), ('MM', 'Marketing Management'), ('HLAM', 'Humanities, Leadership, and Advanced Management'), ('OM', 'Operations Management'), ('STR', 'Strategy'), ('IS', 'Information Systems'), ('ECON', 'Economics')], max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='elective',
            name='area',
            field=models.CharField(blank=True, choices=[('FAC', 'Finance, Accounting, and Control'), ('MM', 'Marketing Management'), ('HLAM', 'Humanities, Leadership, and Advanced Management'), ('OM', 'Operations Management'), ('STR', 'Strategy'), ('IS', 'Information Systems'), ('ECON', 'Economics')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='elective',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor'),
        ),
    ]
