# Generated by Django 6.0 on 2025-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sociallinks_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='area',
            field=models.CharField(blank=True, choices=[('FAC', 'Finance, Accounting, and Control'), ('MM', 'Marketing Management'), ('HLAM', 'Humanities, Liberal Arts, and Management'), ('STR', 'Strategy'), ('IS', 'Information Systems'), ('ECON', 'Economics'), ('QMOM', 'Quantitative Methods and Operations Management'), ('HR', 'Human Resources')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='area',
            field=models.CharField(blank=True, choices=[('FAC', 'Finance, Accounting, and Control'), ('MM', 'Marketing Management'), ('HLAM', 'Humanities, Liberal Arts, and Management'), ('STR', 'Strategy'), ('IS', 'Information Systems'), ('ECON', 'Economics'), ('QMOM', 'Quantitative Methods and Operations Management'), ('HR', 'Human Resources')], max_length=50, null=True),
        ),
    ]
