# Generated by Django 6.0 on 2025-12-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sociallinks_instagram_alter_sociallinks_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
