# Generated by Django 6.0 on 2026-01-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sociallinks_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudycCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('TG', 'Telangana'), ('TN', 'Tamil Nadu'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('geo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyCentrePOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studyccenter')),
            ],
        ),
    ]
