# Generated by Django 6.0 on 2026-01-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_studyccenter_studycentrepoc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudycCenter',
            new_name='StudyCenter',
        ),
    ]
