# Generated by Django 6.0 on 2026-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_studyccenter_studycenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycenter',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
