# Generated by Django 6.0 on 2026-01-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_studycenter_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchinfo',
            name='studyCenterCity',
        ),
        migrations.RemoveField(
            model_name='batchinfo',
            name='studyCenterName',
        ),
        migrations.RemoveField(
            model_name='batchinfo',
            name='studyCenterState',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='studyCenter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_info_sc', to='api.studycenter'),
        ),
        migrations.AlterField(
            model_name='studycenter',
            name='state',
            field=models.CharField(choices=[('AS', 'Assam'), ('AP', 'Andra Pradesh'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('CH', 'Chandigarh'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('TG', 'Telangana'), ('TN', 'Tamil Nadu'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=2),
        ),
    ]
